server:
  port: 8080
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.context: WARN
    org.springframework.beans: WARN
    org.example: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: WARN

spring:
  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/
      printer:
        enabled: true
  main:
    log-startup-info: true